### PR TITLE
Strings for Simplified Chinese

### PR DESCRIPTION
**Pull request by sr093906**

### CODE REVIEW

**Comment by zouroboros** [comment]
Thank you very much for your translation and I am happy to merge your pull request. Could you add the missing translation for the `result_notification_content` string?

**Comment by zouroboros** [comment]
Yes that is indeed a typo I will fix it and merge your changes thank you very much for the translations. If you don't mind I will add your name to the list of contributors.

**Comment by zouroboros** [comment]
I merged the changes via #37.

**Comment by sr093906** [comment]
@zouroboros Thanks.

**Pull request closed without merging**
